import type { NecessaryPart, Order } from "./types";

export const demoParts: NecessaryPart[] = [
  {
    jobId: "JOB-1042",
    partId: "P-EL-90-2IN",
    description: 'Elbow 90° 2" Sch 40 CS',
    requestedQuantity: 8,
    plannedQuantity: 10,
    shippedQuantity: 8,
    missingQuantity: 0,
    reconciliationResult: "OK",
    analysisDate: "2026-07-10",
    status: "OK",
  },
  {
    jobId: "JOB-1042",
    partId: "P-FLG-150-3IN",
    description: 'Flange WN 150# 3" RF',
    requestedQuantity: 12,
    plannedQuantity: 12,
    shippedQuantity: 7,
    missingQuantity: 5,
    reconciliationResult: "FALTANTE",
    analysisDate: "2026-07-10",
    status: "Pendente",
  },
  {
    jobId: "JOB-1042",
    partId: "P-VG-4IN",
    description: 'Gate Valve 4" 300#',
    requestedQuantity: 3,
    plannedQuantity: 3,
    shippedQuantity: 2,
    missingQuantity: 1,
    reconciliationResult: "PARCIAL",
    analysisDate: "2026-07-10",
    status: "Pendente",
  },
  {
    jobId: "JOB-1198",
    partId: "P-TEE-2IN",
    description: 'Tee 2" Sch 80 CS',
    requestedQuantity: 6,
    plannedQuantity: 6,
    shippedQuantity: 6,
    missingQuantity: 0,
    reconciliationResult: "OK",
    analysisDate: "2026-07-12",
    status: "OK",
  },
  {
    jobId: "JOB-1198",
    partId: "P-PIPE-6IN",
    description: 'Pipe 6" Sch 40 CS x 6m',
    requestedQuantity: 20,
    plannedQuantity: 24,
    shippedQuantity: 14,
    missingQuantity: 6,
    reconciliationResult: "FALTANTE",
    analysisDate: "2026-07-12",
    status: "Pendente",
  },
];

export const demoOrders: Order[] = [
  {
    orderId: "PO-2026-0001",
    jobId: "JOB-1042",
    partId: "P-FLG-150-3IN",
    description: 'Flange WN 150# 3" RF',
    missingQuantity: 5,
    origin: "Nacional",
    orderStatus: "Comprado",
    orderDate: "2026-07-11",
    expectedDeliveryDate: "2026-07-25",
    supplier: "MetalSul Ltda.",
    responsible: "A. Ferreira",
    notes: "Prioridade alta",
  },
  {
    orderId: "PO-2026-0002",
    jobId: "JOB-1042",
    partId: "P-VG-4IN",
    description: 'Gate Valve 4" 300#',
    missingQuantity: 1,
    origin: "Internacional",
    orderStatus: "Em cotação",
    orderDate: "2026-07-11",
    expectedDeliveryDate: "",
    supplier: "",
    responsible: "R. Souza",
    notes: "",
  },
  {
    orderId: "PO-2026-0003",
    jobId: "JOB-1198",
    partId: "P-PIPE-6IN",
    description: 'Pipe 6" Sch 40 CS x 6m',
    missingQuantity: 6,
    origin: "Nacional",
    orderStatus: "Recebido",
    orderDate: "2026-07-13",
    expectedDeliveryDate: "2026-07-20",
    supplier: "Tubopar",
    responsible: "M. Lima",
    notes: "Recebido conforme NF 45231",
  },
];
